### ISSUE TITLE
Data Types

### ISSUE THREAD

**Issue by YutaMatsumoto** [citrin2013/citrin#11]
If we wanted to support other data types than just numbers, we should make it happen as soon as possible sine we are hardcoding var_type everywhere. If we defer it, we get more things to fix later.

**Comment by citrin2013** [comment]
Var_type should be where we support more than just numbers. It's not currently set up for it. It'll take some rewriting and adding code, maybe subclasses, but that should all go into var_type. It's not too much work to set var_type up for reference types, pointers, classes. The code in the interpreter expects var_type to be able to handle most of that stuff, except for maybe calling overloaded operators, that should probably happen in the expression evaluator.

**Comment by YutaMatsumoto** [comment]
Yes. That is exactly what I mean. It's not set up yet. That means its interface is going to change and we are embedding code that will be obsolete when the interface is updated. For example, DataDisplay has the following code

var_type v = s.getData();
final Object[][] row = { { v.var_name, v.value} }; 

This piece of code require changes and everywhere else we use var_type. var_type has public fields that we access directly. But if we accommodate more data types, v.value will be something different and should not be accessed directly. We should encapsulate data, by public methods.

**Comment by citrin2013** [comment]
Okay, I see what you mean. I originally knew that it should be public functions as interfaces but, I didn't understand the various parts well enough to know what is needed and how it should be implemented... so I've been putting it off.
