### ISSUE TITLE
Save As is not automatically called, when save is clicked on a new file.

### ISSUE THREAD

**Issue by citrin2013** [citrin2013/citrin#18]
If you type new code without opening a file and hit save instead of save as you get a null pointer exception.

**Comment by jjhall89** [comment]
I'm assuming this has been resolved since this is not happening in the most updated version. Or there's something else going on. please close the issue if the save function now works for you. or comment if it's still now working because it really should be working.

**Comment by jjhall89** [comment]
I made some changes to the Save  and SaveAs functionality. Everything should be working ok. Please comment if it's not.

**Comment by citrin2013** [comment]
It's working.
